# Generated by Django 6.0.2 on 2026-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='saved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
