# Generated by Django 6.0.2 on 2026-02-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_is_transfer_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
