# Generated by Django 6.0.2 on 2026-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción breve')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link de la noticia o video')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Link de la imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
